//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ils
    {
        public int Id { get; set; }
        public string Sehir { get; set; }
        public string PlakaKodu { get; set; }
        public string TelefonKodu { get; set; }
    }
}
