//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisi
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string soyad { get; set; }
        public string Dtarihi { get; set; }
        public string Telefon { get; set; }
    }
}
