//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehir
    {
        public int SehirId { get; set; }
        public string SehirAdi { get; set; }
        public string PlakaKodu { get; set; }
    }
}
