// <auto-generated />
namespace EfCodefirstApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _08042019Sehir : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08042019Sehir));
        
        string IMigrationMetadata.Id
        {
            get { return "201904081416476_08042019Sehir"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
